-- EQ Might overlay: server-unique nameds and any mob with server-specific immunities (overlay overrides base).
return {
    ["anguish"] = {
        { name = "Administrator Charial",   elementalImmunities = { Cold = true, }, },
        { name = "Arch Magus Vangl",        elementalImmunities = { Fire = true, Cold = true, Poison = true, Disease = true, }, },
        { name = "Damlin Lingering Charge", elementalImmunities = { Fire = true, }, },
        "First Lieutentent Minas",
        { name = "Glyphhoarder Krjsta", elementalImmunities = { Magic = true, },                                            statusImmunities = { Slow = true, }, },
        { name = "Keldovan the Harrier", elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, Disease = true, }, },
        { name = "Overlord Mata Muram", elementalImmunities = { Fire = true, Cold = true, Poison = true, Disease = true, }, },
        { name = "Tanthi the Tormentor", elementalImmunities = { Magic = true, }, },
        { name = "Tantho the Tormentor", elementalImmunities = { Fire = true, }, },
        { name = "Tanthu the Tormentor", elementalImmunities = { Cold = true, }, },
        { name = "Ture",                 elementalImmunities = { Fire = true, Cold = true, }, },
        { name = "Vilria the Keeper",   elementalImmunities = { Fire = true, }, },
        "Vipera Ashenheart",
        { name = "Warden Hanvar",       elementalImmunities = { Disease = true, }, },
    },
    ["arcstone"] = {
        "Champion Ultharas",
        "Coalshade, Oroshars Wake",
        { name = "Embra",                    statusImmunities = { Slow = true, }, },
        { name = "The Colossus of Skylance", statusImmunities = { Slow = true, }, },
    },
    ["barren"] = {
        "Mina the Misereable",
        "The Fabled Agrima",
        "Xonda Nelda of Kerrae",
    },
    ["blackburrow"] = {
        "The Fabled Master Brewer",
        "The Mannan of the Sabertooth",
        "The Master Brewer",
    },
    ["bothunder"] = {
        { name = "Emmerik Skyfury",           elementalImmunities = { Cold = true, Disease = true, }, },
        { name = "The Fabled Auliffe Chaoswind", statusImmunities = { Slow = true, }, },
        { name = "The Fabled Bordir Bjomolf", elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Brynju Thunderclap", elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Eindride Icestorm", elementalImmunities = { Cold = true, }, },
        "The Fabled Erech Eyford",
        { name = "The Fabled Gaukr Sandstrom",   elementalImmunities = { Disease = true, }, },
        { name = "The Fabled Hreidar Lynhillig", elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Kuanbyr Hailstorm", elementalImmunities = { Disease = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Laef Windfall",     elementalImmunities = { Cold = true, },    statusImmunities = { Slow = true, }, },
        { name = "The Fabled Oreen Wavecrasher", elementalImmunities = { Cold = true, },    statusImmunities = { Slow = true, }, },
        "The Fabled Valbrand",
        { name = "The Fabled Wybjorn",            elementalImmunities = { Fire = true, }, },
    },
    ["broodlands"] = {
        { name = "Grel Strongboom", statusImmunities = { Snare = true, }, },
        "The Broodqueen",
    },
    ["buriedsea"] = {
        { name = "Blacksail Bob", statusImmunities = { Slow = true, }, },
        { name = "Caroline",      statusImmunities = { Slow = true, }, },
        "Friar Jack",
        { name = "Garayy Yuundu", statusImmunities = { Slow = true, }, },
        { name = "Glolden Ghost", statusImmunities = { Slow = true, }, },
        "Helushka",
        { name = "Manat, Archmage of Redfeather", statusImmunities = { Slow = true, }, },
        { name = "Rentless Ruth",                 statusImmunities = { Slow = true, }, },
        { name = "Shellara Songweaver",           statusImmunities = { Slow = true, }, },
    },
    ["burningwood"] = {
        "Ixiblat Fer",
    },
    ["charasis"] = {
        "The Fabled Crypt Excavator",
        "The Fabled Crypt Spectre",
        "The Fabled Drusella Sathir",
        "The Fabled Skeletal Procurator",
    },
    ["citymist"] = {
        { name = "Neh`Ashiir",            elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, Disease = true, }, },
        { name = "The Fabled Neh`Ashiir", elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, Disease = true, }, },
    },
    ["codecay"] = {
        { name = "Bertoxxulous", elementalImmunities = { Disease = true, }, statusImmunities = { Slow = true, }, },
    },
    ["corathusa"] = {
        "Antraygus, the Sporali King",
    },
    ["crystallos"] = {
        { name = "a fire keeper",            named = false,                          elementalImmunities = { Fire = true, }, }, -- name suspect, verify in-game
        { name = "an azure drakeling",       named = false,                          statusImmunities = { Slow = true, }, },    -- name suspect, verify in-game
        { name = "Chief Researcher Entharr", statusImmunities = { Slow = true, }, },
        { name = "Construct of Zeixshi-Kar", named = false,                          elementalImmunities = { Cold = true, },    statusImmunities = { Slow = true, }, },
        { name = "Dar`Kelor",                elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
        { name = "Elder Earth Drake",        named = false,                          elementalImmunities = { Disease = true, }, },
        { name = "Elder Fire Drake",         named = false,                          elementalImmunities = { Fire = true, }, }, -- name suspect, verify in-game
        { name = "Heart of the Avalanche",   elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
        { name = "Icyyr",                    elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
        "Immortal Sentinel of Kerafyrm",
        { name = "Keeper of the Stones",     statusImmunities = { Slow = true, }, },
        "Kerafyrm the Awakened",
        { name = "Ki`Mrash",                 elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
        "Kildrukaun the Ancient Prophet",
        { name = "Rockcrush",         elementalImmunities = { Cold = true, },    statusImmunities = { Slow = true, }, },
        { name = "Squire Alkaa",      elementalImmunities = { Fire = true, }, },
        { name = "Squire Tectoran",   elementalImmunities = { Fire = true, },    statusImmunities = { Slow = true, }, },
        { name = "Squire Torrentus",  elementalImmunities = { Cold = true, }, },
        { name = "Squire Zirkanamef", elementalImmunities = { Disease = true, }, },
        "The Mightforged Sentinel of Crystallos",
        "Tjudawos the Ancient",
        "Zeixshi'Kar",
    },
    ["delvea"] = {
        { name = "Spider Broodmother", elementalImmunities = { Fire = true, }, },
        { name = "Stonemaw",           elementalImmunities = { Fire = true, }, },
        { name = "Volkara",            elementalImmunities = { Fire = true, }, },
    },
    ["delveb"] = {
        { name = "Emoush the Destroyer", elementalImmunities = { Fire = true, Magic = true, Poison = true, Disease = true, }, },
        "Goblin Hall Guardian",
        { name = "Tirranun",             elementalImmunities = { Fire = true, }, },
    },
    ["devastation"] = {
        "Bartol the Cragmaker",
        { name = "Drishak, the Malevolent", elementalImmunities = { Fire = true, }, },
        { name = "Nydiran the Unrelenting", elementalImmunities = { Magic = true, }, },
        { name = "Savage Fury Lars Hanagar", statusImmunities = { Slow = true, }, },
        "Savage Fury Marie Gronsmar",
        { name = "Titanothon",               statusImmunities = { Slow = true, }, },
    },
    ["devastationa"] = {
        { name = "Ailerie the Magnificent", elementalImmunities = { Magic = true, }, statusImmunities = { Slow = true, }, },
        "Katog the Deviating",
        "Krynor the Feeder",
        "Soulbright, the Essence of Life",
        "Xywil, the Tree of Life",
    },
    ["direwind"] = {
        { name = "Hammerfist the Champion", statusImmunities = { Slow = true, }, },
        { name = "Kendra the Archer",       statusImmunities = { Slow = true, }, },
        { name = "Pyre Lord Narseekin",     statusImmunities = { Slow = true, }, },
    },
    ["drachnidhive"] = {
        "Zummbuk the Vengeful",
    },
    ["dragoncrypt"] = {
        "Frenzied Heretic",
        "Skaramatra the Fallen",
        { name = "Skaramatra the Risen", statusImmunities = { Slow = true, }, },
    },
    ["dreadlands"] = {
        { name = "Gorenaire",            elementalImmunities = { Cold = true, }, },
        { name = "The Fabled Gorenaire", statusImmunities = { Slow = true, }, },
    },
    ["eastwastes"] = {
        { name = "Egg Hunter",            statusImmunities = { Slow = true, }, },
        { name = "The Fabled Snow Bunny", statusImmunities = { Slow = true, }, },
    },
    ["elddar"] = {
        { name = "Animist Yeoh",    statusImmunities = { Slow = true, }, },
        "Cerhan the Wild",
        "Clergyman Jaynen",
        { name = "Geomancer Unala", statusImmunities = { Slow = true, }, },
        "Loyalist Tobey",
        "Strategist Guldar",
        { name = "Volwen the Unkempt", statusImmunities = { Slow = true, }, },
    },
    ["elddara"] = {
        { name = "a priest of Ro", statusImmunities = { Slow = true, }, },
        "Guardian of the High Priest",
        "The Night Huntress",
    },
    ["emeraldjungle"] = {
        { name = "Severilous",            elementalImmunities = { Poison = true, Disease = true, }, },
        { name = "The Fabled Severilous", statusImmunities = { Slow = true, }, },
        "The Ultrafabled Severilous",
    },
    ["everfrost"] = {
        "Icebane",
        "The Ultrafabled Iceberg",
        "The Ultrafabled Thundra Jack",
        { name = "Tundra Jack", elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, Disease = true, }, statusImmunities = { Slow = true, }, },
        "Tuskbreaker",
    },
    ["fearplane"] = {
        { name = "Cazic Thule", statusImmunities = { Slow = true, }, },
        { name = "Dracoliche",  named = false,                       elementalImmunities = { Poison = true, Disease = true, }, },
    },
    ["ferubi"] = {
        "Master`s Apprentice",
        { name = "Smith Rondo", statusImmunities = { Slow = true, }, },
        "Weapon Master Vtiink Vzaan",
    },
    ["fungusgrove"] = {
        "The Fabled Priest Kak`thak",
        "The Fabled Warlord Tk`kik`tthik",
    },
    ["greatdivide"] = {
        "The Fabled Icetooth",
    },
    ["griegsend"] = {
        "Grieg Veneficius",
    },
    ["growthplane"] = {
        "The Ultrafabled Rumbleroot",
        "Timeless Idol of War",
        { name = "Tunare", elementalImmunities = { Poison = true, Disease = true, }, },
    },
    ["gukbottom"] = {
        { name = "a timeless ghoul remnant", statusImmunities = { Slow = true, }, },
        "The Fabled Evil Eye",
        { name = "The Fabled Frenzied Ghoul", elementalImmunities = { Magic = true, }, },
        "The Fabled Froglok Noble",
        "The Fabled Ghoul Cavalier",
        "The Fabled Ghoul Executioner",
        "The Fabled Ghoul Lord",
        "The Fabled Minotaur Patriarch",
        { name = "The Midnight Martriarch",  elementalImmunities = { Poison = true, }, },
        "Timeless Evil Eye",
        { name = "Timeless Frenzied Ghoul",   statusImmunities = { Slow = true, }, },
        { name = "Timeless Froglok Noble",    statusImmunities = { Slow = true, }, },
        { name = "Timeless Ghoul Assassin",   statusImmunities = { Slow = true, }, },
        "Timeless Ghoul Cavalier",
        "Timeless Ghoul Lord",
        "Timeless Minotaur Patriarch",
    },
    ["hateplane"] = {
        "Dark Apostle",
        { name = "Innoruuk", statusImmunities = { Slow = true, }, },
        "The Fabled Master of Spite",
    },
    ["hateplaneb"] = {
        { name = "The Timeless Deathrot Knight", elementalImmunities = { Magic = true, }, },
        "The Ultrafabled Master of Spite",
        { name = "Timeless Arcanist V`Gimis", statusImmunities = { Slow = true, }, },
        { name = "Timeless Assassin Z`Jrix",  statusImmunities = { Slow = true, }, },
        "Timeless Avatar of Abhorrence",
        "Timeless Dread Lord M`Noxin",
        "Timeless Evangelist",
        "Timeless Hand of the Maestro",
        { name = "Timeless Innoruuk",            statusImmunities = { Slow = true, }, },
        { name = "Timeless Maestro of Rancor", statusImmunities = { Slow = true, }, },
        "Timeless Mistress of Malevolence",
    },
    ["hohonorb"] = {
        "Lord Mithaniel Marr",
        "Ralthazor",
        { name = "Ralthazor, Fabled Champion of Marr", statusImmunities = { Slow = true, }, },
        { name = "The Fabled Bromal Rythat",           statusImmunities = { Slow = true, }, },
        "The Fabled Lord Mithaniel Marr",
        "The Fabled Rydda`Dar",
    },
    ["icefall"] = {
        { name = "Avalanche", elementalImmunities = { Cold = true, }, },
        { name = "Glacier",   elementalImmunities = { Cold = true, }, },
        { name = "Grock Mist Seer",                statusImmunities = { Slow = true, }, },
        { name = "Ironeyes",                       statusImmunities = { Slow = true, }, },
        { name = "Nightmoon Chieftain Blacktooth", statusImmunities = { Slow = true, }, },
        { name = "Nightmoon Chieftain Snowmane",   statusImmunities = { Slow = true, }, },
    },
    ["ikkinz"] = {
        { name = "Altar Construct",     statusImmunities = { Slow = true, }, },
        { name = "Altar Warden",               statusImmunities = { Slow = true, }, },
        { name = "Crumbling Monolith",         statusImmunities = { Slow = true, }, },
        { name = "Custodian of Righteousness", statusImmunities = { Slow = true, }, },
        { name = "Guardian of Glorification",  statusImmunities = { Slow = true, }, },
        { name = "Guardian of Righteousness",  statusImmunities = { Slow = true, }, },
        { name = "Guardian of Transcendence",  statusImmunities = { Slow = true, }, },
        { name = "Keeper of the Altar", statusImmunities = { Slow = true, }, },
        { name = "Sentinel of Glorification",  statusImmunities = { Slow = true, }, },
        { name = "Spirit of Tunik Tamuik",     statusImmunities = { Slow = true, }, },
        { name = "Visionary of Glory",         statusImmunities = { Slow = true, }, },
        { name = "Vrex Xalkak Nixki",          statusImmunities = { Slow = true, }, },
    },
    ["inktuta"] = {
        { name = "cursebearer",                  statusImmunities = { Slow = true, }, },
        { name = "Kelekdrix, Herald of Trushar", statusImmunities = { Slow = true, }, },
        { name = "Mirror Image of Noqufiel",     statusImmunities = { Slow = true, }, },
        { name = "True Image of Noqufiel",       statusImmunities = { Slow = true, }, },
    },
    ["kael"] = {
        { name = "Chief Adjutant Isabella",           elementalImmunities = { Cold = true, }, },
        { name = "Deraktor the Vindicator",           elementalImmunities = { Cold = true, },               statusImmunities = { Slow = true, }, },
        { name = "Forsaken Efreeti of Kael",          elementalImmunities = { Cold = true, Magic = true, }, statusImmunities = { Slow = true, }, },
        "Hsagra, The Green Dragoness",
        { name = "King Tormax",                       elementalImmunities = { Cold = true, },               statusImmunities = { Slow = true, }, },
        { name = "Queen Tarmax",                      elementalImmunities = { Cold = true, },               statusImmunities = { Slow = true, }, },
        { name = "The Avatar of War",                 elementalImmunities = { Fire = true, },               statusImmunities = { Slow = true, }, },
        { name = "The Fabled Avatar of War", elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Derakor the Vindicator", elementalImmunities = { Cold = true, },               statusImmunities = { Slow = true, }, },
        "The Fabled Fjoka Frozenshard",
        "The Fabled Idol of Rallos Zek",
        { name = "The Fabled Kallis Stormcaller",  elementalImmunities = { Cold = true, }, },
        { name = "The Fabled King Tormax",         elementalImmunities = { Cold = true, },               statusImmunities = { Slow = true, }, },
        { name = "The Fabled Klraggek the Slayer", elementalImmunities = { Cold = true, Magic = true, }, },
        { name = "The Fabled Queen Tarmax",  elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
        "The Fabled Statue of Rallos Zek",
        "The Idol of Rallos Zek",
        "Timeless Avatar of War",
        { name = "Timeless Deraktor the Vindicator", statusImmunities = { Slow = true, }, },
        "Timeless Idol of Rallos Zek",
        { name = "Timeless King Tormax",             statusImmunities = { Slow = true, }, },
        "Timeless Statue of Rallos Zek",
        "Ultrafabled Queen Tarmax",
    },
    ["karnor"] = {
        "The Fabled Construct of Sathir",
        "The Fabled Decaying Prisoner",
        { name = "The Fabled Drolvarg Captain",   statusImmunities = { Slow = true, }, },
        "The Fabled Drolvarg Warlord",
        "The Fabled Knight of Sathir",
        { name = "The Fabled Senior Drolvarg Captain", statusImmunities = { Slow = true, }, },
        "The Fabled Skeletal Captain",
        { name = "The Fabled Skeletal Fury",           statusImmunities = { Slow = true, }, },
        "The Fabled Skeletal Warlord",
        "The Fabled Undead Jailer",
        { name = "The Fabled Venril Sathir",           statusImmunities = { Slow = true, }, },
        { name = "The Mightforged Sentinel of Karnor", statusImmunities = { Slow = true, }, },
        "The Ultrafabled Drolvarg Captain",
        { name = "The Ultrafabled Skeletal Fury", statusImmunities = { Slow = true, }, },
        { name = "Venril Sathir",                      statusImmunities = { Slow = true, }, },
    },
    ["kedge"] = {
        "The Fabled Estrella of Gloomwater",
        { name = "The Fabled Undertow", statusImmunities = { Slow = true, }, },
    },
    ["kodtaz"] = {
        { name = "Hexxt Chaos Provoker",          statusImmunities = { Slow = true, }, },
        { name = "The Fabled Pixtt Airstrangler", statusImmunities = { Slow = true, }, },
    },
    ["maidensgrave"] = {
        { name = "Nyxaria, the Abyssal Maiden", statusImmunities = { Slow = true, }, },
    },
    ["mesa"] = {
        "Bashmaker",
        "Bigone",
        { name = "Glyphhoarder Gloombranch",    statusImmunities = { Slow = true, }, },
        "Nestor",
        "Peretaenu",
        { name = "Schelet",                statusImmunities = { Slow = true, }, },
        "Shade of Glenicae",
        { name = "Tarsiit Movila",         statusImmunities = { Slow = true, }, },
        { name = "Ternsmochin",            statusImmunities = { Slow = true, }, },
        { name = "The Fabled Ternsmochin", statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Ternsmochin", statusImmunities = { Slow = true, }, },
        "Vorasarpex",
    },
    ["mirc"] = {
        "Ancient Amalgam",
        "Ancient Seer Venos",
        { name = "Ancient Warlord Petrad", elementalImmunities = { Cold = true, }, },
        { name = "Avalara Frostgrave",     statusImmunities = { Slow = true, }, },
        { name = "Black Ice Slime",            elementalImmunities = { Disease = true, },             statusImmunities = { Slow = true, }, },
        { name = "Devouring Vortex",       statusImmunities = { Slow = true, }, },
        "Echo of Synarcana",
        { name = "Enchanted Ice Golem",       elementalImmunities = { Cold = true, }, },
        { name = "Frenzied Ice Goblin",       elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
        { name = "Frostfoot Dynamite Master", elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
        { name = "Legend of the Spider Den",   elementalImmunities = { Cold = true, }, },
        "Mighty White Widow",
        { name = "Mutated Glyphhoarder",       statusImmunities = { Slow = true, }, },
        { name = "Myth of the Spider Den",     elementalImmunities = { Cold = true, }, },
        "Nik the Frozen Heroslayer",
        { name = "Skeletal Assassin",          statusImmunities = { Slow = true, }, },
        "Skeletal Champion",
        "Skeletal Fury",
        { name = "Skeletal Monk",              statusImmunities = { Slow = true, }, },
        { name = "Voras the Spider Matriarch", elementalImmunities = { Cold = true, Poison = true, }, },
    },
    ["mistmoore"] = {
        "The Fabled Cloaked Dhampyre",
        "The Fabled Lasna Cheroone",
        "The Fabled Maid Issis",
        "The Ultrafabled Lasna Cheroone",
    },
    ["mmcd"] = {
        { name = "an immortal shade",        named = false,                       elementalImmunities = { Fire = true, Poison = true, Disease = true, }, },
        "Bloodstice",
        "Count Drakvish",
        { name = "Madame Chiasa",         statusImmunities = { Slow = true, }, },
        { name = "Nightrage Sanguinarch", statusImmunities = { Slow = true, }, elementalImmunities = { Cold = true, Magic = true, Poison = true, Disease = true, }, },
        { name = "Queen Vaelrosa Nyxfang",   statusImmunities = { Slow = true, }, },
        "Scion Radical",
        { name = "Shade of Chiasa",          statusImmunities = { Slow = true, }, elementalImmunities = { Fire = true, Poison = true, Disease = true, }, },
        { name = "Shade of Sage of Death",   statusImmunities = { Slow = true, }, elementalImmunities = { Fire = true, Poison = true, Disease = true, }, },
        { name = "The Sage of Death",        statusImmunities = { Slow = true, }, },
        { name = "The Silent Pianist",       statusImmunities = { Slow = true, }, },
        { name = "Trysta the Dark Tutor",    statusImmunities = { Slow = true, }, },
        { name = "Vaelin Grimlore the Dead", statusImmunities = { Slow = true, }, },
    },
    ["nadox"] = {
        { name = "an immortal black gate sentinel", statusImmunities = { Slow = true, }, },
        { name = "Glyphhoarder Issus",              elementalImmunities = { Magic = true, }, statusImmunities = { Slow = true, }, },
        { name = "Harvester of Souls",              statusImmunities = { Slow = true, }, },
        { name = "Morvath, Soul Tyrant of Nadox",   statusImmunities = { Slow = true, }, },
        { name = "The Dread Archivist",             statusImmunities = { Slow = true, }, },
    },
    ["necropolis"] = {
        { name = "Zlandicar", elementalImmunities = { Poison = true, Disease = true, }, },
    },
    ["northkarana"] = {
        "GrimBeak",
        "GrimClaw",
        "GrimEye",
    },
    ["oasis"] = {
        "The Fabled Lockjaw",
        "The Fabled Phezel",
        { name = "The Ultrafabled Arthikus", statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Phezel",   statusImmunities = { Slow = true, }, },
        "Timeless Cazel",
        { name = "Timeless Lockjaw",         statusImmunities = { Slow = true, }, },
    },
    ["oldblackburrow"] = {
        { name = "Blackburrow Nightstalker", statusImmunities = { Slow = true, }, },
        { name = "Bloodreaper Veschtar",     statusImmunities = { Slow = true, }, },
        "Enraged Gnoll Glyphhoarder",
        "Enraged Gnoll High Commander",
        { name = "Garght the Angry",     statusImmunities = { Slow = true, }, },
        "Gnarl Sawbones Brankt",
        "High Shaman LoEszch",
        { name = "Rottrued the Twisted", statusImmunities = { Slow = true, }, },
    },
    ["permafrost"] = {
        { name = "Emperor Thon`Nex", statusImmunities = { Slow = true, }, },
        "Ice Goblin Philosopher",
        { name = "Ice Goblin Slave Master", statusImmunities = { Slow = true, }, },
        { name = "Lady Vox",         elementalImmunities = { Cold = true, }, },
        { name = "Lady Vox` Sister",        elementalImmunities = { Cold = true, }, },
        "Queen Ahex`Ka",
        "The Fabled Chilling Terror",
        "The Fabled Elite Honor Guard",
        "The Fabled Ice Goblin Alchemist",
        "The Fabled Ice Witch",
        { name = "The Fabled Lady Vox", elementalImmunities = { Cold = true, }, },
        "The Fabled Queen Ahex`Ka",
    },
    ["poair"] = {
        "Avatar of Dust",
        "Avatar of Mist",
        "Avatar of Smoke",
        "Xegony",
    },
    ["podisease"] = {
        "Aramin the Fabled Spider Guardian",
        { name = "Grummus",                    statusImmunities = { Slow = true, }, },
        { name = "The Fabled Arachnae Parian", elementalImmunities = { Disease = true, }, },
        "The Fabled Diseased Infested Bubonian",
        { name = "The Fabled Grummus",          statusImmunities = { Slow = true, }, },
        "The Fabled Malerian Metamo",
        { name = "The Fabled Rallius Rattican", elementalImmunities = { Disease = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Sengian Fly",      statusImmunities = { Slow = true, }, },
        "The Fabled Skals Waking Nightmare",
    },
    ["poeartha"] = {
        "A Fabled Mystical Arbitor of Earth",
        { name = "A Fabled Perfected Warder of Earth", statusImmunities = { Slow = true, }, },
        "A Fabled Prismatic Basilisk",
        "An Earthen Undercon",
        { name = "An Encrusted Dirt Cloud",            statusImmunities = { Slow = true, }, },
        "A Merciless Mudslinger",
        "A Mystical Arbitor of Earth",
        { name = "Peregrin Rockskull", statusImmunities = { Slow = true, }, },
    },
    ["poearthb"] = {
        "a Rathe Council Man",
        "The Avatar of Earth",
        { name = "War Chieftan Galronar", elementalImmunities = { Disease = true, }, },
        "Warlord Gintolaken",
    },
    ["pofire"] = {
        "A Fabled Doomfire Chaoslord",
        { name = "Fennin Ro",                 elementalImmunities = { Fire = true, }, },
        { name = "Hebabbilys the Ragelord",   elementalImmunities = { Fire = true, }, },
        "Lord Infernon",
        { name = "Magmaton",                  elementalImmunities = { Fire = true, Magic = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Arch Mage Yozanni",         elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Azobian the Darklord",      elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Babnoxis the Spider Queen", elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Blazzax the Omnifiend",     elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Chancellor Kirta",          elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Chancellor Traxom",         elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Dark Obsidian Lava Spider", elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Doomfire Magus",            elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Fennin Ro, Tyrant of Fire", elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled General Reparm", elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Guardian of Doomfire",      elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Hebabbilys the Ragelord",   elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Javonn the Overlord",     elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Magma Overlord",          elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Magmaton",                elementalImmunities = { Fire = true, Magic = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Omni Magus Crato",        statusImmunities = { Slow = true, }, },
        { name = "The Fabled Quavonis Firetail",       elementalImmunities = { Fire = true, },               statusImmunities = { Slow = true, }, },
        { name = "The Fabled Reaxnous the Chaoslord",  elementalImmunities = { Fire = true, },               statusImmunities = { Slow = true, }, },
        { name = "The Fabled Vicar of Fire",  elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Warlord Prollaz",         statusImmunities = { Slow = true, }, },
        { name = "The Fabled Wild Fiery Spirit Steed", statusImmunities = { Slow = true, }, },
        { name = "The Lavaforged Behemoth", elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        "The Ultrafabled Magmaton",
    },
    ["potactics"] = {
        "Ancient Statue of War",
        "Deathbringer Rianit",
        { name = "Diaku Elite Myrmidon",   statusImmunities = { Slow = true, }, },
        "Guardian of the Halls",
        { name = "Hendin Shadow Mistress", statusImmunities = { Slow = true, }, },
        { name = "Hendin Slavemonger",     statusImmunities = { Slow = true, }, },
        { name = "Rallos Zek", statusImmunities = { Slow = true, }, },
        { name = "Sullon Mclarren",        statusImmunities = { Slow = true, }, },
        { name = "Tallon Zek", statusImmunities = { Slow = true, }, },
        "The Fabled Anival the Blade",
        "The Fabled Deadly Warboar",
        { name = "The Fabled Deathbringer Blackheart", statusImmunities = { Slow = true, }, },
        { name = "The Fabled Diaku Armorer",           statusImmunities = { Slow = true, }, },
        "The Fabled Guardian of the Halls",
        { name = "The Fabled Tallon Zek",          statusImmunities = { Slow = true, }, },
        { name = "The Fabled Vallon Zek",          statusImmunities = { Slow = true, }, },
        { name = "The Fabled Warlord, Rallos Zek", statusImmunities = { Slow = true, }, },
        { name = "Vallon Zek",             statusImmunities = { Slow = true, }, },
    },
    ["potimeb"] = {
        { name = "Bertoxxulous",          elementalImmunities = { Disease = true, }, statusImmunities = { Slow = true, }, },
        { name = "Cazic Thule",           statusImmunities = { Slow = true, }, },
        { name = "Innoruuk",              statusImmunities = { Slow = true, }, },
        { name = "Rallos Zek",            statusImmunities = { Slow = true, }, },
        { name = "Saryrn",                statusImmunities = { Slow = true, }, },
        { name = "Supernatural Guardian", statusImmunities = { Slow = true, }, },
        { name = "Tallon Zek",            statusImmunities = { Slow = true, }, },
        { name = "Terris Thule",          statusImmunities = { Slow = true, }, },
        { name = "Vallon Zek",            statusImmunities = { Slow = true, }, },
    },
    ["potorment"] = {
        "Maareq the Fabled Prophet",
        { name = "Saryrn",                           statusImmunities = { Slow = true, }, },
        { name = "The Fabled Acolyte of Affliction", statusImmunities = { Slow = true, }, },
        { name = "The Fabled Salczek the Fleshgrinder", statusImmunities = { Slow = true, }, },
        "The Fabled Sorrowsong",
        "The Fabled Ta`Grusch",
    },
    ["powater"] = {
        { name = "Coirnav",                      elementalImmunities = { Cold = true, }, },
        { name = "Krziik the Mighty",            elementalImmunities = { Cold = true, }, },
        { name = "The Fabled Krziik the Mighty", elementalImmunities = { Cold = true, }, },
    },
    ["provinggrounds"] = {
        "Master of Versatility",
    },
    ["qeynos2"] = {
        "The Fabled Fippy Darkpaw",
        "The Ultrafabled Fippy Darkpaw",
        "The Ultrafabled Nixx Darkpaw",
    },
    ["qvic"] = {
        { name = "Dvoin M`sha",        statusImmunities = { Slow = true, }, },
        { name = "Iqthinxa Karnkvi",   statusImmunities = { Slow = true, }, },
        "Krag`Thul the Fabled Bonebreaker",
        { name = "Mnat M`sha",         statusImmunities = { Slow = true, }, },
        { name = "Ptav M`sha",         statusImmunities = { Slow = true, }, },
        "The Fabled Cynosure Kvanjji",
        "The Fabled Dvoin M`sha",
        { name = "The Fabled Iqthinxa Karnkvi", statusImmunities = { Slow = true, }, },
        { name = "The Fabled Pixtt Invi Mal",   statusImmunities = { Slow = true, }, },
        "The Fabled Pixtt Llan Kvish",
        { name = "The Fabled Zun`Hexxt Jkak Miq", statusImmunities = { Slow = true, }, },
        "The Fabled Zun`Hexxt Pvin Nki",
        { name = "Zun`Hexxt Jkak Miq", statusImmunities = { Slow = true, }, },
        "Zun`Hexxt Pvin Nki",
        "Zun`Pixtt Invi Mal",
        "Zun`Pixtt Llan Kvish",
    },
    ["rage"] = {
        "Ar`yer the Warlord",
        "Jarl Hedmar",
        { name = "Jarl Pinvul", statusImmunities = { Slow = true, }, },
        "Jarl Ytarin",
        { name = "Mengalor",         statusImmunities = { Slow = true, }, },
        "Savage Fury Grogmaul",
        "The Skulltaker",
        { name = "Yoon the Gleener", statusImmunities = { Slow = true, }, },
    },
    ["ragea"] = {
        "Ghost, Guardian of Razorthorn",
        "Snowtail, Guardian of Razorthorn",
        { name = "Sullon Zek, Mistress of Rage", statusImmunities = { Slow = true, }, },
    },
    ["rathemtn"] = {
        "Chieftain Eyclopse",
    },
    ["relic"] = {
        { name = "a crashing wave",     elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "a demented scrykin",  statusImmunities = { Slow = true, }, },
        { name = "a scrykin firestorm", statusImmunities = { Slow = true, }, },
        { name = "Ashenback",           elementalImmunities = { Fire = true, }, },
        { name = "Maru the Twelfth Born", statusImmunities = { Slow = true, }, },
        "Nightshade",
        "Porthio the Second Born",
        "The Guardian of the Doorway",
    },
    ["riftseekers"] = {
        { name = "Channeler Pyren", elementalImmunities = { Fire = true, }, },
        { name = "King Gelequa",    elementalImmunities = { Cold = true, Magic = true, }, },
        { name = "Queen Pyrilonis", elementalImmunities = { Fire = true, Magic = true, }, },
        { name = "Shadowstalker",   elementalImmunities = { Cold = true, }, },
    },
    ["ruja"] = {
        "a Steelslave Slayer",
        { name = "Baat Groobsmash",        statusImmunities = { Slow = true, }, },
        { name = "Drogar the Indomitable", statusImmunities = { Slow = true, }, },
        "Golbi the Goblin Patriarch",
        "Huur'Ay",
        "Legend of Bloodied Quarries",
        "Lurzz",
        "Schagraat",
        "Sikl the Slayer of Men",
        "Steelslave Brute",
        "Steelslave Crusher",
        { name = "Steelslave Marauder",                  statusImmunities = { Slow = true, }, },
        "Steelslave Smasher",
        { name = "Summoran", elementalImmunities = { Magic = true, }, statusImmunities = { Slow = true, }, },
        { name = "Summoran's Uncontrollable Experiment", statusImmunities = { Slow = true, }, },
        "The King of the Ring",
        "Tulla Groobsmash",
        "Ugluuk",
        "Warmistress Skoora",
    },
    ["sebilis"] = {
        { name = "Ancient Myconid Spore Empress", statusImmunities = { Slow = true, }, },
        "Froglok Maak Knight",
        "Sebilis Protector",
        { name = "Spectral Assassin of Chottal",  statusImmunities = { Slow = true, }, },
        "The Fabled Baron Yosig",
        "The Fabled Brogg",
        "The Fabled Emperor Chottal",
        "The Fabled Froglok Bartender",
        "The Fabled Froglok Chef",
        "The Fabled Gruplinort",
        "The Fabled Harbinger Freglor",
        "The Fabled Hierophant Prime Grekal",
        "The Fabled Myconid Spore King",
        "The Fabled Myconid Warrior",
        "The Fabled Sebilite Guardian",
        "The Fabled Sebilite Protector",
        "The Fabled Skeletal Crusader",
        { name = "The Fabled Trakanon",             elementalImmunities = { Poison = true, Disease = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Skeletal Crusader",             statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Arch Duke Latol", statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Baron Yosig",     statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Emperor Chottal", statusImmunities = { Slow = true, }, },
        "The Ultrafabled Ninja Froglok",
        "The Ultrafabled Sebilis Warrior",
        { name = "The Ultrafabled Spectral Assassin", statusImmunities = { Slow = true, }, },
        "Timeless Brogg",
        { name = "Timeless Froglok Bartender",       statusImmunities = { Slow = true, }, },
        "Timeless Froglok Chef",
        "Timeless Gangrenous Scarab",
        "Timeless Gruplinort",
        { name = "Timeless Harbinger Freglor",       statusImmunities = { Slow = true, }, },
        { name = "Timeless Hierophant Prime Grekal", statusImmunities = { Slow = true, }, },
        "Timeless Myconid Spellguard",
        { name = "Timeless Myconid Spore Empress", statusImmunities = { Slow = true, }, },
        { name = "Timeless Revenant Duchess",      statusImmunities = { Slow = true, }, },
        "Timeless Sebilite Guardian",
        { name = "Timeless Sebilite Protector", statusImmunities = { Slow = true, }, },
        "Timeless Tolapumj",
        "Timeless Trakanon",
        { name = "Trakanon",                      elementalImmunities = { Poison = true, Disease = true, }, },
    },
    ["sirens"] = {
        "Felicita of Darkwater",
        { name = "Fellspine",            elementalImmunities = { Cold = true, }, },
        { name = "The Fabled Fellspine", elementalImmunities = { Cold = true, }, },
    },
    ["skyfire"] = {
        { name = "The Ultrafabled Talendor", statusImmunities = { Slow = true, }, },
    },
    ["skyshrine"] = {
        { name = "Lord Yelinak", elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
    },
    ["sleeper"] = {
        { name = "The Fabled Progenitor",           elementalImmunities = { Cold = true, },              statusImmunities = { Slow = true, }, },
        { name = "The Fabled Vyskudra the Ancient", elementalImmunities = { Fire = true, }, },
        { name = "The Final Arbiter",               elementalImmunities = { Fire = true, Cold = true, }, },
        { name = "The Progenitor",                  elementalImmunities = { Cold = true, },              statusImmunities = { Slow = true, }, },
        { name = "Vyskudra the Ancient", elementalImmunities = { Fire = true, }, },
    },
    ["soldungb"] = {
        { name = "Efreeti Lord Djarn", elementalImmunities = { Fire = true, }, },
        { name = "King Tranix",        elementalImmunities = { Fire = true, }, },
        { name = "Lord Nagafen",       elementalImmunities = { Fire = true, }, },
        "The Fabled Death Beetle",
        "The Fabled Efreeti Lord Djarn",
        { name = "The Fabled Efreeti Lord Djarn II", elementalImmunities = { Fire = true, }, },
        "The Fabled King Tranix",
        "The Fabled King Tranix II",
        "The Fabled Kobold Noble",
        { name = "The Fabled Lord Nagafen",          elementalImmunities = { Fire = true, }, },
        "The Fabled Magus Rokyl",
        "The Fabled Magus Rokyl II",
        { name = "The Fabled Neiroth",                  elementalImmunities = { Fire = true, }, },
        "The Fabled Solusek Queen",
        "The Fabled Warlord Skarlon",
        "The Fabled Warlord Skarlon II",
        { name = "Zordak Ragefire the Ashen Conqueror", statusImmunities = { Slow = true, }, },
    },
    ["solrotower"] = {
        { name = "Conjured Automoton",               elementalImmunities = { Fire = true, }, },
        { name = "Elite Guardian of Ro",             named = false,                          elementalImmunities = { Fire = true, }, },
        { name = "Jiva",                             elementalImmunities = { Fire = true, }, },
        { name = "Solusek Ro",                       elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Arlyxir",               elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Galremos",              elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Jiva",                  elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Naelizar",              elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Protector of Dresolik", elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Quazlith",              elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Rizlona",               elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Solusek Ro",            elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Veleroth",              elementalImmunities = { Fire = true, }, },
        { name = "The Fabled Xuzl",                  elementalImmunities = { Fire = true, }, },
        { name = "The Protector of Dresolik",        elementalImmunities = { Fire = true, }, },
    },
    ["solteris"] = {
        { name = "a living flame",                named = false,                          elementalImmunities = { Fire = true, }, },
        "Althea",
        { name = "Aprosis the Fourth Confidant",  statusImmunities = { Slow = true, }, },
        { name = "Aspect of Ambition",            named = false,                          elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "Aspect of Courage",             named = false,                          elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "Aspect of Devotion",            named = false,                          elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "Aspect of Fortitude",           named = false,                          elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "Aspect of Justice",             named = false,                          elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "Aspect of Resourcefulness",     named = false,                          elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "Aspect of Temperance",          named = false,                          elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "Aspect of Wisdom",              named = false,                          elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "Astire, the Lunar Eclipse",     statusImmunities = { Slow = true, }, },
        "Athena",
        { name = "Brenda",    statusImmunities = { Slow = true, }, },
        { name = "Christine", statusImmunities = { Slow = true, }, },
        { name = "Commodus, Solar Construct",     elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "Guardian of the Eighth Prime",  statusImmunities = { Slow = true, }, },
        { name = "Guardian of the Fifth Prime",   elementalImmunities = { Magic = true, Disease = true, }, },
        "Guardian of the First Prime",
        { name = "Guardian of the Fourth Prime",  statusImmunities = { Slow = true, }, },
        "Guardian of the Ninth Prime",
        { name = "Guardian of the Second Prime",  statusImmunities = { Slow = true, }, },
        { name = "Guardian of the Seventh Prime", statusImmunities = { Slow = true, }, },
        { name = "Guardian of the Sixth Prime",   elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, Disease = true, }, statusImmunities = { Slow = true, }, },
        "Guardian of the Third Prime",
        { name = "Irrissa the Seer",              statusImmunities = { Slow = true, }, },
        { name = "Mayong Mistmoore",              statusImmunities = { Slow = true, }, }, -- not a typo/duplicate. spawns during sol ro fight
        { name = "Mayong Mistmoore the Darkness", statusImmunities = { Slow = true, }, },
        { name = "Rear Guard Captain Balreth",    statusImmunities = { Slow = true, }, },
        { name = "Solusek Ro The Burning Prince", elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        "Stonewatcher of the Ten",
        { name = "Ur-Floxiz Lochmaul",            statusImmunities = { Slow = true, }, },
    },
    ["southkarana"] = {
        "The Fabled Darkpaw",
        "The Fabled Gnashmaw",
        "The Fabled Grizzleknot",
        { name = "The Fabled Groi Gutblade", statusImmunities = { Slow = true, }, },
        "The Fabled Grusch Val Gnoll",
        "The Fabled Ishva Mal",
        "The Fabled Kroldir Thunderhoof",
        { name = "The Fabled Lord Grimrot",  statusImmunities = { Slow = true, }, },
        "The Fabled Mroon",
        "The Fabled Quillmane",
        "The Fabled Synger Foxfyre",
        "The Fabled Tesch Val Deval Nmak",
        "The Fabled Varishe Mal Judge",
    },
    ["sseru"] = {
        { name = "Lord Inquisitor Seru", elementalImmunities = { Magic = true, }, },
    },
    ["ssratemple"] = {
        { name = "Arch Lich Rhag`Zadune", elementalImmunities = { Poison = true, Disease = true, }, statusImmunities = { Slow = true, }, },
        "Blood Golem",
        { name = "Emperor Ssraeshza",     elementalImmunities = { Poison = true, }, },
        "Glyph covered serpent",
        "Vyzh`dra the Cursed",
    },
    ["stillmoona"] = {
        "Animated Granite Colossus",
        "Animated Granite Guardian",
        "Animated Granite Titan",
        "Celeste the Silent Paw",
        { name = "Cinderella",           elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, Disease = true, }, statusImmunities = { Slow = true, }, },
        { name = "Grimblade Skittermaw", elementalImmunities = { Poison = true, }, },
        "Hartini the Smart",
        "Icehoof",
        "Nocturna the Stealth Striker",
        "Roqzar the Sapphire Roar",
        "Seraphis",
        "Solstice the Firemane",
        "Stormmane Thunderhoof",
        "The Mightforged Sentinel of Stillmoon",
        "Thornheart the Mighty Stallion",
        "Valrakor the Fiery Stallion",
        "Valrator the Fiery Stallion",
        "Villy the Golden",
        "Volaris the Sharp",
        "Voltaris the Sharp",
    },
    ["stillmoonb"] = {
        "Razortail",
    },
    ["sunderock"] = {
        { name = "Darkmist", statusImmunities = { Slow = true, }, },
        "Sentinel of Sunderrock",
    },
    ["tacvi"] = {
        "The Fabled Llan Kvish",
    },
    ["taka"] = {
        { name = "A Sunbane Seductress", named = false,                       statusImmunities = { Slow = true, }, },
        "Avatar of Dust",
        "Dunebreaker",
        "Flowkeeper Berta",
        "Geomancer Blackquill",
        { name = "Glyphhoarder Kinso",   statusImmunities = { Slow = true, }, },
        "Gravitus Gargantua",
        "Ignatius the Fallen Paladin", -- Scarab add
        "Ignatius the Scorched Scarab",
        { name = "Lucinda the Luminous Ladybug", statusImmunities = { Slow = true, }, },
        "Mistral", -- Sirocco add, need to kill fast.
        { name = "Petrified Desert Treant",      statusImmunities = { Slow = true, }, },
        { name = "Sandbound Sentinel",           statusImmunities = { Slow = true, }, },
        { name = "Sirocco",                      statusImmunities = { Slow = true, }, },
    },
    ["takishruins"] = {
        "Architect Enelde",
        "Bookkeeper Molly",
        { name = "Cirwea Strongbow", statusImmunities = { Slow = true, }, },
        "Flowkeeper Nicyn",
        "Foreman Araz",
        { name = "Gravewalker",      statusImmunities = { Slow = true, }, },
        "Lieutenant Tuffy",
        { name = "Night Terror", statusImmunities = { Slow = true, }, },
        "Thex Widow",
    },
    ["takishruinsa"] = {
        "Beau`Draa the false Warden",
        "Fippy Firepaw",
    },
    ["templeveeshan"] = {
        { name = "Dagarn the Destroyer", elementalImmunities = { Fire = true, }, },
        { name = "Eashen of the Sky",    elementalImmunities = { Cold = true, },   statusImmunities = { Slow = true, }, },
        { name = "Ikatiar the Venom",    elementalImmunities = { Poison = true, }, statusImmunities = { Slow = true, }, },
        { name = "Lady Mirenilla", elementalImmunities = { Poison = true, }, },
        { name = "Lord Kreizenn",  elementalImmunities = { Fire = true, Cold = true, }, statusImmunities = { Slow = true, }, },
        { name = "Lord Vyemm",                   elementalImmunities = { Cold = true, Magic = true, Poison = true, }, },
        { name = "The Fabled Eashen of the Sky", elementalImmunities = { Cold = true, },                                              statusImmunities = { Slow = true, }, },
        { name = "The Fabled Gozzrem",           elementalImmunities = { Fire = true, Magic = true, Poison = true, Disease = true, }, statusImmunities = { Slow = true, }, },
        { name = "Vulak`Aerr",                   elementalImmunities = { Poison = true, Disease = true, }, },
    },
    ["thalassius"] = {
        { name = "Kraj Iurolapos",   statusImmunities = { Slow = true, }, },
        { name = "Phyrael Mollotus", statusImmunities = { Slow = true, }, },
        { name = "Rockcrusher",      statusImmunities = { Slow = true, }, },
        { name = "Wavecrasher",      statusImmunities = { Slow = true, }, },
    },
    ["theater"] = {
        "Aesthir the Delusioned",
        { name = "Anastasia the Thought Drinker", statusImmunities = { Slow = true, }, },
        "Belinda Baleheart",
        { name = "Bleeding Storm",                statusImmunities = { Slow = true, }, },
        "Fangore Boneclaw",
        { name = "Illixis, the Dark Dream", statusImmunities = { Slow = true, }, },
        "Leafrot",
        { name = "Lilia, the Rancid",       statusImmunities = { Slow = true, }, },
        "Master Chrichus",
        "Mistress of Malady",
        "Painscreecher",
        "Seraphino the Fierce",
        "Shatterstyr",
        { name = "Sir Savagery", statusImmunities = { Slow = true, }, },
        { name = "Talili",       statusImmunities = { Slow = true, }, },
        "The Festering",
    },
    ["theatera"] = {
        { name = "Ashtar", statusImmunities = { Slow = true, }, },
        { name = "Melkis", statusImmunities = { Slow = true, }, },
        { name = "T`Pall", statusImmunities = { Slow = true, }, },
        { name = "Truefaith Bat Keeper",  statusImmunities = { Slow = true, }, },
        { name = "Truefaith Beastmaster", statusImmunities = { Slow = true, }, },
    },
    ["thegrey"] = {
        "The Fabled Boulder",
        "The Fabled Crusader Kezza",
        "The Fabled Heirophant Grazan",
        "The Fabled Revenant Sthzzzizt",
        "The Fabled Revenant Zsshta",
        "The Pathless Sentinel",
        "The Ultrafabled Revenant Sthzzzizt",
        "The Ultrafabled Revenant Zsshta",
    },
    ["thenest"] = {
        "Ancient Ainslin",
        { name = "Ancient Lavawalker", elementalImmunities = { Fire = true, }, },
        { name = "Ancient Magmeran",   elementalImmunities = { Fire = true, }, },
        "Ancient Tremblor",
        "Aquila the Sharp",
        "Drake Magus",
        { name = "Lavawalker", elementalImmunities = { Fire = true, }, },
        { name = "Magmeran",   elementalImmunities = { Fire = true, }, },
        "T'Shara",
        { name = "Vishimtar", elementalImmunities = { Disease = true, }, },
    },
    ["thundercrest"] = {
        "Yar'Lir",
    },
    ["thurgadinb"] = {
        { name = "Dain Frostreaver IV", elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
    },
    ["toskirakk"] = {
        { name = "Aureon the Gleamforged Juggernaut", elementalImmunities = { Magic = true, Poison = true, Disease = true, }, statusImmunities = { Slow = true, }, },
        { name = "Brusk of Oggok",  statusImmunities = { Slow = true, }, },
        { name = "Ganekk Dopp",     statusImmunities = { Slow = true, }, },
        { name = "General Arblok",  statusImmunities = { Slow = true, }, },
        { name = "General Bardak",  statusImmunities = { Slow = true, }, },
        { name = "General Grusix",  statusImmunities = { Slow = true, }, },
        { name = "General Lobroan", statusImmunities = { Slow = true, }, },
        { name = "Glyphhoarder Kanxor",               statusImmunities = { Slow = true, }, },
        { name = "Gorvash Bloodmarauder, Shadow of Zek", statusImmunities = { Slow = true, }, },
        { name = "Ragnarok Steelwrath, Warlord of Zek", statusImmunities = { Slow = true, }, },
        { name = "Rallos Zek",                        statusImmunities = { Slow = true, }, },
        { name = "Tonkk the Axestopper",                statusImmunities = { Slow = true, }, },
        { name = "Ulgren Vith",                         statusImmunities = { Slow = true, }, },
        { name = "Vessa the Oracle",                    statusImmunities = { Slow = true, }, },
        { name = "Vorruk Skullcleaver, Fury of Zek",     statusImmunities = { Slow = true, }, },
        "Ward Sergeant Krug",
        "Ward Sergeant Razzok",
        "Ward Sergeant Ulgok",
        "Warden Gulgreth",
        "Zharog Bonecleaver",
    },
    ["txevu"] = {
        { name = "Ancient Cragbeast Matriarch", statusImmunities = { Slow = true, }, },
        { name = "Ikaav Nysf Lleiv",            elementalImmunities = { Poison = true, }, },
        { name = "Ixt Kial Ivesi",  statusImmunities = { Slow = true, }, },
        { name = "Ixt Quall Nalnn", statusImmunities = { Slow = true, }, },
        { name = "Zun`Muram Tkarish Zyk", elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, Disease = true, }, },
    },
    ["umbral"] = {
        { name = "Doomshade",                        elementalImmunities = { Poison = true, Disease = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Bloodwretch",           elementalImmunities = { Disease = true, }, },
        { name = "The Fabled Doomshade",             elementalImmunities = { Poison = true, Disease = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Elysian Elder",         elementalImmunities = { Disease = true, }, },
        "The Fabled Fallen Sergeant",
        { name = "The Fabled Fleshrot",               statusImmunities = { Slow = true, }, },
        { name = "The Fabled Netherbian Swarmcaller", elementalImmunities = { Disease = true, },                statusImmunities = { Slow = true, }, },
        { name = "The Fabled Netherbian Swarmcrier", elementalImmunities = { Disease = true, },                statusImmunities = { Slow = true, }, },
        { name = "The Fabled Rumblecrush",            elementalImmunities = { Poison = true, Disease = true, }, },
        { name = "The Fabled Zelnithak",              elementalImmunities = { Disease = true, }, },
        { name = "Zelnithak",                        elementalImmunities = { Disease = true, }, },
    },
    ["uqua"] = {
        "Devastating Construct",
        "Guardian of Destruction",
        { name = "Vrex Barxt Qurat", statusImmunities = { Slow = true, }, },
    },
    ["valdeholm"] = {
        { name = "Animal Tender Bealon", statusImmunities = { Slow = true, }, },
        { name = "Ironbelly",            statusImmunities = { Slow = true, }, },
        { name = "Kangur Vafta Veor",    statusImmunities = { Slow = true, }, },
        "The Void",
        { name = "Thrymfang", statusImmunities = { Slow = true, }, },
    },
    ["veeshan"] = {
        "Ancient Faydrake of Veeshan",
        "Ancient Gatekeeper of Veeshan",
        "Blazetalon the Ancient",
        "Blazetalon the Dragonblooded",
        { name = "Copperwing", elementalImmunities = { Fire = true, Magic = true, Disease = true, }, },
        { name = "Druushk",   elementalImmunities = { Cold = true, }, },
        "Granithide",
        { name = "Lady Dar",                      elementalImmunities = { Magic = true, },                  statusImmunities = { Slow = true, }, },
        { name = "Lady Tay",                      elementalImmunities = { Poison = true, Disease = true, }, },
        { name = "Lavatail",                      elementalImmunities = { Fire = true, }, },
        { name = "Nerro",                         statusImmunities = { Slow = true, }, },
        { name = "Nexona",    elementalImmunities = { Fire = true, }, },
        { name = "Phara Dar", elementalImmunities = { Fire = true, }, },
        { name = "Pyroskarn the Embercoil",       elementalImmunities = { Fire = true, },                   statusImmunities = { Slow = true, }, },
        "Ragnoor the Defender",
        { name = "Thalmyra of the Gleaming Coil", statusImmunities = { Slow = true, }, },
        { name = "The Azure Warden",              elementalImmunities = { Cold = true, }, },
        { name = "Xygoz",      elementalImmunities = { Fire = true, },                               statusImmunities = { Slow = true, }, },
    },
    ["velketor"] = {
        { name = "Bledrek",                              elementalImmunities = { Cold = true, Magic = true, }, },
        { name = "Kerdelb",                              elementalImmunities = { Cold = true, Magic = true, }, },
        { name = "Lord Doljonijiarnimorinar",            elementalImmunities = { Cold = true, },               statusImmunities = { Slow = true, }, },
        { name = "The Brood Mother",      statusImmunities = { Slow = true, }, },
        { name = "The Fabled Bledrek",           elementalImmunities = { Cold = true, Magic = true, }, },
        { name = "The Fabled Crystal Eyes",              elementalImmunities = { Cold = true, }, },
        { name = "The Fabled Crystal Fang",              elementalImmunities = { Cold = true, }, },
        { name = "The Fabled Fierce Blizzard Hunter",    elementalImmunities = { Cold = true, }, },
        { name = "The Fabled Gregendek Icepaw",          elementalImmunities = { Cold = true, }, },
        { name = "The Fabled Kerdelb",           elementalImmunities = { Cold = true, Magic = true, }, },
        { name = "The Fabled Lord Doljonijiarnimorinar", elementalImmunities = { Cold = true, },               statusImmunities = { Slow = true, }, },
        { name = "The Fabled Tijoely",                   elementalImmunities = { Cold = true, }, },
        "The Ultrafabled Blizzard Hunteress",
        "The Ultrafabled Brood Mother",
        "The Ultrafabled Lord Doljonijiarnimorinar",
        "Triumphant Experiment",
        { name = "Velketor the Fabled Sorcerer", elementalImmunities = { Cold = true, },               statusImmunities = { Slow = true, }, },
        { name = "Velketor the Sorcerer", elementalImmunities = { Cold = true, }, },
    },
    ["vexthal"] = {
        "Aten Ha Ra",
        { name = "Diabo Xi Va",           statusImmunities = { Slow = true, }, },
        { name = "Diabo Xi Xin Thall",    statusImmunities = { Slow = true, }, },
        { name = "Kaas Thox Xi Ans Dyek", statusImmunities = { Slow = true, }, },
        { name = "Thall Xundraux Diabo", statusImmunities = { Slow = true, }, },
        "Va Dyn Ra",
    },
    ["wallofslaughter"] = {
        { name = "Cipheron", elementalImmunities = { Fire = true, Cold = true, Magic = true, Poison = true, Disease = true, }, },
    },
    ["westkorlacha"] = {
        "Matriarch Shyra",
        "Overseer Iseek",
    },
    ["westwastes"] = {
        { name = "a deep chaos ice burrower", statusImmunities = { Slow = true, }, },
        { name = "Klandicar", elementalImmunities = { Cold = true, }, },
        "Lady Yzarma",
        { name = "Melalafen", elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        "Mistress Mistrilla",
        { name = "Sontalak",  elementalImmunities = { Fire = true, }, },
        "The Fabled Ayillish",
        "The Fabled Del Sapara",
        { name = "The Fabled Esorpa of the Ring", statusImmunities = { Slow = true, }, },
        "The Fabled Harla Dar",
        "The Fabled Ionat",
        "The Fabled Karkona",
        { name = "The Fabled Klandicar",          elementalImmunities = { Cold = true, }, },
        { name = "The Fabled Melalafen",          elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Fabled Sontalak",           elementalImmunities = { Fire = true, }, },
        "The Fabled Tantor",
        { name = "The Ultrafabled Ayillish",           statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Esorpa of the Ring", statusImmunities = { Slow = true, }, },
        "The Ultrafabled Gangel",
        { name = "The Ultrafabled Harla Dar", statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Hechaeva",  statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Karkona",   statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Klandicar", elementalImmunities = { Cold = true, }, statusImmunities = { Slow = true, }, },
        { name = "The Ultrafabled Melalafen", elementalImmunities = { Fire = true, }, statusImmunities = { Slow = true, }, },
        "The Ultrafabled Sontalak",
        "Timeless Atpaev",
        { name = "Timeless Sontalak", elementalImmunities = { Fire = true, }, },
        "Timeless Strong Horn",
        "Timeless Tantor",
        { name = "Timeless Tranala",  statusImmunities = { Slow = true, }, },
        "Timeless Travala",
        "Timeless Tsiraka",
        "Timeless Zlandicar",
    },
    ["yxtta"] = {
        { name = "Pixtt Suir Mindrider", elementalImmunities = { Fire = true, }, },
        "Primal Hynid Warbeast",
        "Primal Ukun Warhound",
        "The Fabled Pixtt Suir Mindrider",
    },
    ["zhisza"] = {
        { name = "Copperfang", elementalImmunities = { Poison = true, }, },
        { name = "Coralitus",  elementalImmunities = { Poison = true, }, statusImmunities = { Slow = true, }, },
        { name = "Holloweyes", statusImmunities = { Slow = true, }, },
        "King Brownscale",
    },
}
